### PR TITLE
Changed protoc compilation from manual to automated

### PR DESCRIPTION
**Pull request by mheuser**
For easier testing. Also updated the protobuf-java version to 2.6.1. This only affects the testCompile lifecycle.

### CODE REVIEW

**Comment by HiJon89** [comment]
Thanks for the PR! I'll try to review this and #3 some time this week

**Comment by mheuser** [comment]
Any chance to get this and PR #3 merged and published on central.sonatype this week? Else I have to setup my own sonatype for the time being.

**Comment by HiJon89** [comment]
Is 2.6.1 backwards-compatible with 2.5.0? I'm concerned with making this change without a version bump

**Comment by mheuser** [comment]
For my knowledge yes, see also [1]. It seems that 3.0.0 will start breaking compatibility. I am also using 2.5.0, 2.6.0 and 2.6.1 together.

[1]: https://github.com/google/protobuf/blob/master/CHANGES.txt

**Comment by cowtowncoder** [comment]
On compatibility: for what it is worth, compatibility between modules and core is bit different than for external app code. So... officially, the main guarantee is that matching minor versions will work together (i.e. patches never change compatibility). Beyond this, attempts are made to try to keep adjacent versions compatible (so that, f.ex, datatype-protobuf of 2.6 would indeed work with core versions of 2.5, 2.6 and 2.7). But oftentimes modules do depend on new features included in later revisions; and sometimes changes to internal handling do break forwards compatibility (that is, protobuf-2.6 would only work with core 2.6, but not with 2.5).
I realize above sounds pretty... wishy-washy. But I wanted to mention that while for end-user code, 2.x code written for an earlier version will work with later 2.x versions (and this is an explicit goal wrt sem-ver - compatibility), it is not quite guaranteed for module-to-core dependencies.

Given all this, once there is "official" public version of a module, I think it makes sense to have branches for minor versions. I don't know what is the status of this module is, but I am guessing it is not yet official in that sense. So bump is probably fine.

For specific case of 2.6/2.5 however, there are no known breaking changes at this point, and none planned. 2.5 on the other hand did have some fundamental changes from 2.4 (implicit vs explicit property names) that caused issues wrt Scala module.

**Comment by HiJon89** [comment]
Ok good to know. I try to maintain compatibility with all 2.x since we still use 2.1.x internally

**Comment by cowtowncoder** [comment]
It should be relatively easy with `datatype` modules; although may need to use deprecated methods in some cases. Scala module is an extreme case of multiple challenges. So this is probably not a biggie here at all.

Building different versions from different branches is easy enough, too, but obviously more work if bug fixes are to be backported.

**Pull request merged**
