### PR TITLE
Fixed PropertyNamingStrategyWrapper to respect custom PropertyNamingStrategy

### PR DESCRIPTION
**Pull request by mheuser**
If you had protobuf messages with camel case attributes then the json attributes where changed to all lower case when it should be still camel case, even with a custom do nothing PropertyNamingStrategy set.

This pull requests fixes this without changing the default behavior.

### CODE REVIEW

**Comment by HiJon89** [comment]
This LGTM although the protobuf [docs](https://developers.google.com/protocol-buffers/docs/style) make it pretty clear field names should be snake case. This is a superset of #2 right?

**Comment by mheuser** [comment]
Sometimes you have to work with what you get :smile:.  And yes it is.

**Comment by HiJon89** [comment]
Thanks for the PR, I'll release as 0.5.0 today :)

**Comment by mheuser** [comment]
Great, thanks!

**Comment by cowtowncoder** [comment]
Btw, would it make sense at some point to synchronize this with official Jackson releases?
I could release this as part of big release, or just coordinate to get it out after other components.

**Comment by HiJon89** [comment]
Sure, if you ping me or open an issue on Jackson release I can make corresponding releases

**Comment by cowtowncoder** [comment]
Ok; since 2.5.0 was released few weeks back, if you think this module is stable enough, maybe doing 2.5.0 now would make sense? I can coordinate via issue tracker in future. And perhaps there's need for a mailing list, as there are now a few external modules (bson4jackson).

**Comment by HiJon89** [comment]
A mailing list would be nice, I don't check maven central very often so getting notified of Jackson releases would be a big help

**Pull request merged**
